import { useState } from "react";
import { toast } from "sonner";

export function useIdeaActions(ideas, setIdeas) {
  const handleToggleFavorite = async (idea, index) => {
    try {
      const newStatus = !idea.is_favorite;
      const response = await fetch("/api/ideas", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: idea.id, is_favorite: newStatus }),
      });

      if (!response.ok) throw new Error("Failed to update favorite");

      const updatedIdeas = [...ideas];
      updatedIdeas[index] = { ...idea, is_favorite: newStatus };
      setIdeas(updatedIdeas);
      toast.success(
        newStatus ? "Added to favorites!" : "Removed from favorites",
      );
    } catch (err) {
      toast.error("Could not update favorite");
    }
  };

  const handleVote = async (idea, index) => {
    try {
      const res = await fetch("/api/ideas", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "vote", ideaId: idea.id }),
      });

      if (!res.ok) throw new Error("Failed to vote");
      const data = await res.json();

      const updatedIdeas = [...ideas];
      updatedIdeas[index] = {
        ...idea,
        user_has_voted: data.voted,
        vote_count: parseInt(idea.vote_count || 0) + (data.voted ? 1 : -1),
      };
      setIdeas(updatedIdeas);
      toast.success(data.voted ? "Voted!" : "Vote removed");
    } catch (err) {
      toast.error("Could not process vote");
    }
  };

  const handleCopyIdea = (idea) => {
    const text = `${idea.title}\n\n${idea.description}\n\nTarget Audience: ${idea.target_audience}\n\nKey Features:\n${idea.key_features?.map((f) => `- ${f}`).join("\n")}`;
    navigator.clipboard.writeText(text);
    toast.success("Idea copied to clipboard!");
  };

  const handleExportSpec = (idea) => {
    const spec = `
# IdeaForge Spec: ${idea.title}
Generated on: ${new Date().toLocaleDateString()}
Model Source: ${idea.model_source || "IdeaForge AI Engine"}

## 1. Overview
${idea.description}

## 2. Target Audience
${idea.target_audience}

## 3. Key Features
${idea.key_features?.map((f) => `- ${f}`).join("\n")}

## 4. Market Validation Scores
${Object.entries(idea.scores || {})
  .map(([key, val]) => `- ${key.replace("_", " ").toUpperCase()}: ${val}/10`)
  .join("\n")}

## 5. Suggested Tech Stack
- **Frontend**: React / Next.js (Web), React Native / Expo (Mobile)
- **Backend**: Node.js / PostgreSQL
- **Database**: PostgreSQL
- **Styling**: Tailwind CSS / NativeWind
- **AI Integration**: OpenAI / Anthropic / Gemini

## 6. Build Instructions
1. **Setup**: Initialize a new project using your preferred framework.
2. **Database Schema**: Create tables for users, ${idea.title.toLowerCase().replace(/\s+/g, "_")}, and core features.
3. **Core Logic**: Implement the ${idea.key_features?.[0] || "primary feature"} first.
4. **UI/UX**: Focus on a clean, user-centric design matching the target audience.
5. **Deployment**: Deploy to Vercel (Web) or App Store/Play Store (Mobile).

---
Generated by IdeaForge - Turn your sparks into validated startups.
    `;

    const blob = new Blob([spec], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${idea.title.replace(/\s+/g, "_")}_Spec.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return {
    handleToggleFavorite,
    handleVote,
    handleCopyIdea,
    handleExportSpec,
  };
}
